# SimpleImputer  

In [2]:
import numpy as np

In [3]:
from sklearn.impute import SimpleImputer

In [5]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [6]:
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])


SimpleImputer()

In [7]:
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_mean.transform(X))


[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


In [8]:
#################################

In [9]:
from sklearn.impute import SimpleImputer
import numpy as np


In [10]:
imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')

In [11]:
data = [[12, np.nan, 34],
        [10, 32, np.nan],
        [np.nan, 11, 20]]

In [13]:
print("Original Data : \n", data)
# Fitting the data to the imputer object
imputer = imputer.fit(data)

Original Data : 
 [[12, nan, 34], [10, 32, nan], [nan, 11, 20]]


In [15]:
data = imputer.transform(data)
 
print("Imputed Data : \n", data)

Imputed Data : 
 [[12.  21.5 34. ]
 [10.  32.  27. ]
 [11.  11.  20. ]]


In [16]:
################################################

In [17]:
import numpy as np
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(missing_values = 0 ,strategy ='mean')

data = [[12, 0, 34], [10, 32, 0],[0, 11, 20]]
print("Original Data : \n", data)


imputer = imputer.fit(data)
data = imputer.transform(data)
print("Imputed Data : \n", data)


Original Data : 
 [[12, 0, 34], [10, 32, 0], [0, 11, 20]]
Imputed Data : 
 [[12.  21.5 34. ]
 [10.  32.  27. ]
 [11.  11.  20. ]]


In [18]:
#######################################

In [ ]:

import numpy as np
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(missing_values = 0 ,strategy ='mean')

data = [[12, 0, 34], [10, 32, 0],[0, 11, 20]]
print("Original Data : \n", data)


imputer = imputer.fit(data)
data = imputer.transform(data)
print("Imputed Data : \n", data)


In [24]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values= 0 , strategy="median")

data=[  [2 ,0, 10],
        [0, 50 ,16],
        [4 , 50 ,0 ],
        [6 ,50 , 28 ]]
print(data)

[[2, 0, 10], [0, 50, 16], [4, 50, 0], [6, 50, 28]]


In [25]:
imputer =   imputer.fit(data)
data= imputer.transform(data)
print(data)

[[ 2. 50. 10.]
 [ 4. 50. 16.]
 [ 4. 50. 16.]
 [ 6. 50. 28.]]


In [26]:
##############################


In [31]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan ,  strategy="most_frequent")
data= [ ["A" , "B","C","D"] , ["A",np.nan ,"C",'D'], [np.nan ,"B" ,'C','D'],['A' ,'B',np.nan,np.nan] ]
data

[['A', 'B', 'C', 'D'],
 ['A', nan, 'C', 'D'],
 [nan, 'B', 'C', 'D'],
 ['A', 'B', nan, nan]]

In [32]:
imputer = imputer.fit(data)
data =imputer.transform(data)
data

array([['A', 'B', 'C', 'D'],
       ['A', 'B', 'C', 'D'],
       ['A', 'B', 'C', 'D'],
       ['A', 'B', 'C', 'D']], dtype=object)