In [1]:
import numpy as np

In [5]:
security_breaches = np.array([  [0, 5, 1],
                                [0, 2, 0],
                                [1, 1, 2],
                                [2, 2, 1],
                                [0, 0, 0]])
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [8]:
security_breaches.sum()

17

In [9]:
security_breaches.sum(axis=0)

array([ 3, 10,  4])

In [10]:
security_breaches.sum(axis=1)

array([6, 2, 4, 5, 0])

In [11]:
security_breaches.min()

0

In [12]:
security_breaches.max()

5

In [13]:
security_breaches.min(axis=1)


array([0, 0, 1, 1, 0])

In [14]:
security_breaches.min(axis=0)


array([0, 0, 0])

In [15]:
security_breaches.mean()

1.1333333333333333

In [16]:
security_breaches.sum(axis=1)

array([6, 2, 4, 5, 0])

In [17]:
security_breaches.sum(axis=1, keepdims=True)


array([[6],
       [2],
       [4],
       [5],
       [0]])

In [20]:
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [19]:
security_breaches.cumsum(axis=0)

array([[ 0,  5,  1],
       [ 0,  7,  1],
       [ 1,  8,  3],
       [ 3, 10,  4],
       [ 3, 10,  4]], dtype=int32)

In [21]:
security_breaches.cumsum(axis=1)

array([[0, 5, 6],
       [0, 2, 2],
       [1, 2, 4],
       [2, 4, 5],
       [0, 0, 0]], dtype=int32)