In [1]:
import numpy as np 

In [7]:
np.arange(1000000).mean()


499999.5

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])
for row in range(array.shape[0]):
    for column in range(array.shape[1]):
        array[row][column] += 3


In [9]:
array

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [12]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[0, 1, 0], [1, 0, 1]])
array_a + array_b

array([[1, 3, 3],
       [5, 5, 7]])

In [13]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[0, 1, 0], [1, 0, 1]])
array_a * array_b

array([[0, 2, 0],
       [4, 0, 6]])

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [22]:
array = np.array(["NumPy","is","awesome"])
len(array) > 2

True

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
names = np.array([["Izzy", "Monica", "Marvin"],
                  ["Weber", "Patel", "Hernandez"]])

In [35]:
vectorized_upper = np.vectorize(str.upper)

# Apply vectorized_upper to the names array
uppercase_names = vectorized_upper(names)
print(uppercase_names)

[['IZZY' 'MONICA' 'MARVIN']
 ['WEBER' 'PATEL' 'HERNANDEZ']]
