In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [29]:
rgb = np.array([[[255, 0, 0],   [255, 255, 0], [255, 255, 255]],
                [[255, 0, 255], [0, 255, 0],   [0, 255, 255]],
                [[0, 0, 0],     [0, 255, 255], [0, 0, 255]]])
rgb

array([[[255,   0,   0],
        [255, 255,   0],
        [255, 255, 255]],

       [[255,   0, 255],
        [  0, 255,   0],
        [  0, 255, 255]],

       [[  0,   0,   0],
        [  0, 255, 255],
        [  0,   0, 255]]])

In [30]:
red_array = rgb[:, :, 0]
red_array

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])

In [31]:
green_array = rgb[:, :, 1]
green_array

array([[  0, 255, 255],
       [  0, 255, 255],
       [  0, 255,   0]])

In [32]:
blue_array = rgb[:, :, 2]
blue_array

array([[  0,   0, 255],
       [255,   0, 255],
       [  0, 255, 255]])

In [33]:
######

In [34]:
rgb_tt = np.array([[[1, 2, 3],   [4, 5, 6], [7, 8, 9]],
                [[11, 12, 13], [14, 15, 16],   [17 , 18, 19]],
                [[21,22, 23],     [24, 25, 26], [27, 28, 29]]])
rgb_tt

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [46]:
red_array__ = rgb_tt[:, :, 0]
red_array__

array([[ 1,  4,  7],
       [11, 14, 17],
       [21, 24, 27]])

In [52]:
red_array_tt, green_array_tt, blue_array_tt = np.split(rgb_tt, 3, axis=2)
red_array_tt

array([[[ 1],
        [ 4],
        [ 7]],

       [[11],
        [14],
        [17]],

       [[21],
        [24],
        [27]]])

In [53]:
green_array_tt

array([[[ 2],
        [ 5],
        [ 8]],

       [[12],
        [15],
        [18]],

       [[22],
        [25],
        [28]]])

In [37]:
######

In [38]:
red_array, green_array, blue_array = np.split(rgb, 3, axis=2)
red_array

array([[[255],
        [255],
        [255]],

       [[255],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0]]])

In [54]:
red_array

array([[[255],
        [255],
        [255]],

       [[255],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0]]])

In [55]:
red_array_2D = red_array.reshape((3, 3))
red_array_2D

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])

In [56]:
red_array = np.zeros((1001, 1001)).astype(np.int32)
green_array = green_array.reshape((1001, 1001))
blue_array = blue_array.reshape((1001, 1001))

ValueError: cannot reshape array of size 9 into shape (1001,1001)