In [1]:
import numpy as np

In [2]:
one_to_five = np.arange(1, 6)
one_to_five

array([1, 2, 3, 4, 5])

In [4]:
mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False])

In [5]:
one_to_five = np.arange(1, 6)
mask = one_to_five % 2 == 0
one_to_five[mask]

array([2, 4])

In [6]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [7]:
classroom_ids_and_sizes[:, 1] % 2 == 0

array([ True, False, False,  True])

In [8]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [9]:
classroom_ids_and_sizes[:, 0][classroom_ids_and_sizes[:, 1] % 2 == 0]


array([1, 4])

## Filtering with np.where()


In [10]:
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [11]:
np.where(classroom_ids_and_sizes[:, 1] % 2 == 0)

(array([0, 3], dtype=int64),)

In [13]:
sudoku_game= np.array([ [0, 0, 4, 3, 0, 0, 2, 0, 9],
                        [0, 0, 5, 0, 0, 9, 0, 0, 1],
                        [0, 7, 0, 0, 6, 0, 0, 4, 3],
                        [0, 0, 6, 0, 0, 2, 0, 8, 7],
                        [1, 9, 0, 0, 0, 7, 4, 0, 0],
                        [0, 5, 0, 0, 8, 3, 0, 0, 0],
                        [6, 0, 0, 0, 0, 0, 1, 0, 5],
                        [0, 0, 3, 5, 0, 8, 6, 9, 0],
                        [0, 4, 2, 9, 1, 0, 3, 0, 0]])
sudoku_game

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [14]:
row_ind, column_ind = np.where(sudoku_game == 0)
row_ind, column_ind

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8], dtype=int64))

In [18]:
np.where(sudoku_game == 0,99, sudoku_game)

array([[99, 99,  4,  3, 99, 99,  2, 99,  9],
       [99, 99,  5, 99, 99,  9, 99, 99,  1],
       [99,  7, 99, 99,  6, 99, 99,  4,  3],
       [99, 99,  6, 99, 99,  2, 99,  8,  7],
       [ 1,  9, 99, 99, 99,  7,  4, 99, 99],
       [99,  5, 99, 99,  8,  3, 99, 99, 99],
       [ 6, 99, 99, 99, 99, 99,  1, 99,  5],
       [99, 99,  3,  5, 99,  8,  6,  9, 99],
       [99,  4,  2,  9,  1, 99,  3, 99, 99]])