In [1]:
import numpy as np

In [6]:
arr_1 = np.array([[2, 0, 1], [9, 1, 4]])
arr_2 = np.array([[3, 8, 8], [5, 2, 0]])

np.stack([arr_1, arr_2], axis=2)

array([[[2, 3],
        [0, 8],
        [1, 8]],

       [[9, 5],
        [1, 2],
        [4, 0]]])

In [8]:
array1 = np.array([[5, 5, 9], [9, 9, 8]])
array2 = np.array([[6, 5, 8], [3, 3, 8]])
np.concatenate((array1 , array2))

array([[5, 5, 9],
       [9, 9, 8],
       [6, 5, 8],
       [3, 3, 8]])

In [14]:
rgb = np.array([[[255,   0,   0],
                [  0,   0,   0],
                [  0,   0, 255]],

               [[255,   0, 255],
                [255, 255, 255],
                [255, 255,   0]]])
arr_1, arr_2, arr_3 = np.split(rgb, 3, axis=1)
arr_1

array([[[255,   0,   0]],

       [[255,   0, 255]]])

In [17]:
array_2D = np.array([[ 5,  1,  6,  2,  4,  6],
       [ 5,  8,  0,  2,  1,  2],
       [ 2,  9,  6, 23, 13,  1]])
sum_arr = array_2D.sum(axis=0,  reshape =True)

np.concatenate((array_2D, sum_arr))


TypeError: _sum() got an unexpected keyword argument 'reshape'