In [1]:
import numpy as np

In [2]:
python_list = [3, 2, 5, 8, 4, 9, 7, 6, 1]
array = np.array(python_list)
array

array([3, 2, 5, 8, 4, 9, 7, 6, 1])

In [3]:
type(array)


numpy.ndarray

In [4]:
python_list_of_lists = [[3, 2, 5],
                        [9, 7, 1],
                        [4, 3, 6]]
np.array(python_list_of_lists)

array([[3, 2, 5],
       [9, 7, 1],
       [4, 3, 6]])

In [6]:
python_list = ["beep", False, 56, .945, [3, 2, 5]]
python_list

['beep', False, 56, 0.945, [3, 2, 5]]

In [11]:
np.zeros((5, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.random((2, 4))


array([[0.19975718, 0.10266871, 0.98945085, 0.1354361 ],
       [0.88859424, 0.63936681, 0.13415304, 0.12518103]])

In [15]:
np.arange(-3, 4)


array([-3, -2, -1,  0,  1,  2,  3])

In [16]:
np.arange(-3, 4,2)


array([-3, -1,  1,  3])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])